spring:
  profiles:
    active: dev
  application:
    name: qian
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/all
    username: root
    password: 2649940648
    ##session失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    port: 6379
    host: localhost
    password: 2649940648
    database: 0
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑删除默认值
      logic-not-delete-value: 0 #逻辑不删除默认值